export const networks = Object.freeze({
  MAIN_NET: {
    id: 1,
    hex: '0x1',
    name: 'Main Network',
    symbol: '',
    rpcUrl: '',
    explorerUrl: '',
    color: 'green',
    icon: '',
  },
  BINANCE_MAIN_NET: {
    id: 56,
    hex: '0x38',
    name: 'Binance Main Network',
    symbol: '',
    rpcUrl: 'https://bsc-dataseed1.binance.org:443',
    explorerUrl: '',
    color: 'gold',
    icon: '',
  },
  ROPSTEN_TEST_NET: {
    id: 3,
    hex: '0x3',
    name: 'Ropsten Test Network',
    symbol: '',
    rpcUrl: '',
    explorerUrl: '',
    color: 'pink',
    icon: '',
  },
  RINKEBY_TEST_NET: {
    id: 4,
    hex: '0x4',
    name: 'Rinkeby Test Network',
    symbol: '',
    rpcUrl: '',
    explorerUrl: '',
    color: 'yellow',
    icon: '',
  },
  GOERLI_TEST_NET: {
    id: 5,
    hex: '0x5',
    name: 'Goerli Test Network',
    symbol: '',
    rpcUrl: '',
    explorerUrl: '',
    color: 'blue',
    icon: '',
  },
  KOVAN_TEST_NET: {
    id: 42,
    hex: '0x2a',
    name: 'Kovan Test Network',
    symbol: '',
    rpcUrl: '',
    explorerUrl: '',
    color: 'purple',
    icon: '',
  },
  BINANCE_TEST_NET: {
    id: 97,
    hex: '0x61',
    name: 'Binance Test Network',
    symbol: 'BNB',
    rpcUrl: 'https://data-seed-prebsc-1-s1.binance.org:8545/',
    explorerUrl: '',
    color: 'orange',
    icon: '',
  },
  MATIC_MAIN_NET: {
    id: 137,
    hex: '0x137',
    name: 'Matic Main Network',
    symbol: 'MATIC',
    rpcUrl: 'https://rpc-mainnet.maticvigil.com/',
    explorerUrl: 'https://explorer.matic.network/',
    color: 'green',
    icon: '',
  },
  MUMBAI_TEST_NET: {
    id: 80001,
    hex: '0x13881',
    name: 'Mumbai Test Network',
    symbol: 'MATIC',
    rpcUrl: 'https://rpc-mumbai.maticvigil.com/',
    explorerUrl: 'https://mumbai-explorer.matic.today',
    color: 'violet',
    icon: '',
  },
  TRUFFLE_DEV_NET: {
    id: 4447,
    hex: '4447',
    name: 'Truffle Dev Network',
    symbol: '',
    rpcUrl: '',
    explorerUrl: '',
    color: 'red',
    icon: '',
  },
  GANACHE_DEV_NET: {
    id: 5777,
    hex: '5777',
    name: 'Ganache Localhost Dev Network',
    symbol: '',
    rpcUrl: '',
    explorerUrl: '',
    color: 'red',
    icon: '',
  },
  LOCALHOST: {
    id: 8545,
    hex: '8545',
    name: 'Localhost Development',
    symbol: '',
    rpcUrl: '',
    explorerUrl: '',
    color: 'red',
    icon: '',
  },
})
