export const networks = Object.freeze({
  MAIN_NET: {
    id: 1,
    hex: '0x1',
    name: 'Main Network',
    color: 'green',
    icon: '',
  },
  BINANCE_MAIN_NET: {
    id: 2,
    hex: '0x38',
    name: 'Binance Main Network',
    color: 'gold',
    icon: '',
  },
  ROPSTEN_TEST_NET: {
    id: 3,
    hex: '0x3',
    name: 'Ropsten Test Network',
    color: 'pink',
    icon: '',
  },
  RINKEBY_TEST_NET: {
    id: 4,
    hex: '0x4',
    name: 'Rinkeby Test Network',
    color: 'yellow',
    icon: '',
  },
  GOERLI_TEST_NET: {
    id: 5,
    hex: '0x5',
    name: 'Goerli Test Network',
    color: 'blue',
    icon: '',
  },
  KOVAN_TEST_NET: {
    id: 42,
    hex: '0x2a',
    name: 'Kovan Test Network',
    color: 'purple',
    icon: '',
  },
  BINANCE_TEST_NET: {
    id: 61,
    hex: '0x61',
    name: 'Binance Test Network',
    color: 'orange',
    icon: '',
  },
  MUMBAI_TEST_NET: {
    id: 8001,
    hex: '0x13881',
    name: 'Mumbai Test Network',
    color: 'violet',
    icon: '',
  },
  TRUFFLE_DEV_NET: {
    id: 4447,
    hex: '4447',
    name: 'Truffle Dev Network',
    color: 'red',
    icon: '',
  },
  GANACHE_DEV_NET: {
    id: 5777,
    hex: '5777',
    name: 'Ganache Localhost Dev Network',
    color: 'green',
    icon: '',
  },
})
